### ISSUE TITLE
Receiving a feed with no data points raises 404 RequestError

### ISSUE THREAD

**Issue by brentru** [adafruit/Adafruit_IO_Python#119]
Calling `client.receive` on a newly created feed with no data points raises a 404 if no data exists on the feed. 

Update the library to not error on that call with a 404, and instead return a `None` value or a Data type which sets the `value` as `None`:

```
Data(created_epoch=None, created_at='2020-07-10T13:52:52Z', updated_at='2020-07-10T13:52:52Z', value='None', completed_at=None, feed_id=1157950, expiration='1599573172.0', position=None, id='0EG0X017NKRDS5527E3YXN0VP4', lat=None, lon=None, ele=None)
```

Example code

```
# Create an instance of the REST client.
aio = Client(ADAFRUIT_IO_USERNAME, ADAFRUIT_IO_KEY)
try: # i we have a 'digital' feed
    digital = aio.feeds('digital')
except RequestError: # create a digital feed
    feed = Feed(name="digital")
    digital = aio.create_feed(feed)
while True:
    print(digital)
    data = aio.receive(digital.key)
    time.sleep(0.5)
```

Output
```
Traceback (most recent call last):
File "/home/pi/Documents/digital_out.py", line 45, in <module>
data = aio.receive(digital.key)
File "/home/pi/.local/lib/python3.7/site-packages/Adafruit_IO/client.py", line 216, in receive
return Data.from_dict(self._get(path))
File "/home/pi/.local/lib/python3.7/site-packages/Adafruit_IO/client.py", line 118, in _get
self._handle_error(response)
File "/home/pi/.local/lib/python3.7/site-packages/Adafruit_IO/client.py", line 108, in _handle_error
raise RequestError(response)
Adafruit_IO.errors.RequestError: Adafruit IO request failed: 404 Not Found - not found - API documentation can be found at https://io.adafruit.com/api/docs
```

**Comment by BlackLight** [comment]
Not sure if this library is still maintained, but this is a core breaking bug that has been open for at least a year. Is there any plan to tackle it or will someone try and fork the library?

**Comment by RobisLV** [comment]
Can confirm. I am experiencing the same bug.

`>>> aio.receive("myfeed")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/adafruit_io-2.5.0-py3.7.egg/Adafruit_IO/client.py", line 216, in receive
  File "/usr/local/lib/python3.7/dist-packages/adafruit_io-2.5.0-py3.7.egg/Adafruit_IO/client.py", line 118, in _get
  File "/usr/local/lib/python3.7/dist-packages/adafruit_io-2.5.0-py3.7.egg/Adafruit_IO/client.py", line 108, in _handle_error
Adafruit_IO.errors.RequestError: Adafruit IO request failed: 404 Not Found - not found - API documentation can be found at https://io.adafruit.com/api/docs
`

**Comment by brunofcat** [comment]
the same issue.

**Comment by tyeth** [comment]
Just spotted this issue, I should have probably fixed it instead of fixing the example in https://github.com/adafruit/Adafruit_IO_Python/pull/160 🤦 
Added to my list.

**Comment by lorennorman** [comment]
This error is happening when a feed has no data, yet. The API responds with 404 and a generic "not found" error, leaving the Python client to die without much info.

Just now, the IO team has updated the error messages for some of these data messages. Specifically the method:
```
aio.receive(feed_key)
```

will say "This feed has not published any data, yet.", which more clearly explains what is happening to the user.

I believe @tyeth may also want to update the client itself to notice such errors and improve the behavior. It could catch these, emit a warning message, and return `None`, for example.
