### ISSUE TITLE
io.adafruit.com

### ISSUE THREAD

**Issue by Infyskybelgaum** [adafruit/Adafruit_IO_Python#127]
I am facing this issue please help me here . not getting what is happening 

Traceback (most recent call last):
  File "mq6flame.py", line 58, in <module>
    gas_feed = aio.feeds('mq6_gas')
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_IO/client.py", line 274, in feeds
    return Feed.from_dict(self._get(path))
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_IO/client.py", line 118, in _get
    self._handle_error(response)
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_IO/client.py", line 108, in _handle_error
    raise RequestError(response)
Adafruit_IO.errors.RequestError: Adafruit IO request failed: 404 Not Found - not found - that is an invalid URL, please check the API documentation at https://io.adafruit.com/api/docs to make sure your URL is correct

**Comment by nicvc** [comment]
The underscore in your feed name `mq6_gas` might cause the problem. The feed key will be `mq6-gas`. The Python client has no proper way to handle this as of today. It will use `mq6_gas` for the url, but the correct url contains the key, not the name. I recommend to use only characters that are allowed for feed keys:

> The only characters we permit are lower case english letters ("a" to "z"), numbers, and dash ("-").
