### ISSUE TITLE
Adafruit_IO.errors.RequestError: Adafruit IO request failed: 404 Not Found - not found

### ISSUE THREAD

**Issue by mczteinaz** [adafruit/Adafruit_IO_Python#159]
- Platform/operating system (i.e. Raspberry Pi with Raspbian operating system,
  Windows 32-bit, Windows 64-bit, Mac OSX 64-bit, etc.):  

**
pi@newpi4os:~ $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
**

- Python version (run `python -version` or `python3 --version`):  
**
python3 --version
Python 3.11.2
**

- Error message you are receiving, including any Python exception traces: 
 **
>>> %Run new_digi_out.py
Traceback (most recent call last):
  File "/home/pi/io-client-python/examples/basics/new_digi_out.py", line 43, in <module>
    data = aio.receive(digital.key)
  File "/home/pi/.local/lib/python3.11/site-packages/Adafruit_IO/client.py", line 254, in receive
    return Data.from_dict(self._get(path))
  File "/home/pi/.local/lib/python3.11/site-packages/Adafruit_IO/client.py", line 132, in _get
    self._handle_error(response)
  File "/home/pi/.local/lib/python3.11/site-packages/Adafruit_IO/client.py", line 120, in _handle_error
    raise RequestError(response)
Adafruit_IO.errors.RequestError: Adafruit IO request failed: 404 Not Found - not found - API documentation can be found at https://io.adafruit.com/api/docs
>>> 
**

- List the steps to reproduce the problem below (if possible attach code or commands
  to run): 

**
Follow digital_output tutorial from https://learn.adafruit.com/adafruit-io-basics-digital-output/python-code

**

Following digital_output tutorial from https://learn.adafruit.com/adafruit-io-basics-digital-output/python-code

Running this code:

"""
'digital_out.py'
===================================
Example of turning on and off a LED
from the Adafruit IO Python Client

Author(s): Brent Rubell, Todd Treece
"""
# Import standard python modules
import time

# import Adafruit Blinka
import digitalio
import board

# import Adafruit IO REST client.
from Adafruit_IO import Client, Feed, RequestError

# Set to your Adafruit IO key.
# Remember, your key is a secret,
# so make sure not to publish it when you publish this code!
ADAFRUIT_IO_KEY = 'YOUR_AIO_KEY'

# Set to your Adafruit IO username.
# (go to https://accounts.adafruit.com to find your username)
ADAFRUIT_IO_USERNAME = 'YOUR_AIO_USERNAME'

# Create an instance of the REST client.
aio = Client(ADAFRUIT_IO_USERNAME, ADAFRUIT_IO_KEY)

try: # if we have a 'digital' feed
    digital = aio.feeds('digital')
except RequestError: # create a digital feed
    feed = Feed(name="digital")
    digital = aio.create_feed(feed)

# led set up
led = digitalio.DigitalInOut(board.D5)
led.direction = digitalio.Direction.OUTPUT

while True:
    data = aio.receive(digital.key)
    if int(data.value) == 1:
        print('received <- ON\n')
    elif int(data.value) == 0:
        print('received <- OFF\n')

    # set the LED to the feed value
    led.value = int(data.value)
    # timeout so we dont flood adafruit-io with requests
    time.sleep(0.5)

From multiple Raspberry Pi devices and Operating System installations, always results in the error:

>>> %Run new_digi_out.py
Traceback (most recent call last):
  File "/home/pi/io-client-python/examples/basics/new_digi_out.py", line 43, in <module>
    data = aio.receive(digital.key)
  File "/home/pi/.local/lib/python3.11/site-packages/Adafruit_IO/client.py", line 254, in receive
    return Data.from_dict(self._get(path))
  File "/home/pi/.local/lib/python3.11/site-packages/Adafruit_IO/client.py", line 132, in _get
    self._handle_error(response)
  File "/home/pi/.local/lib/python3.11/site-packages/Adafruit_IO/client.py", line 120, in _handle_error
    raise RequestError(response)
Adafruit_IO.errors.RequestError: Adafruit IO request failed: 404 Not Found - not found - API documentation can be found at https://io.adafruit.com/api/docs
>>>

**Comment by tyeth** [comment]
@mczteinaz thanks for reporting this, there are a couple of possibilities that come to mind...
 The most likely is that the previous guide in the series (digital input) uses the same feed key, and has sent data to the `digital` feed when you run the digital input example. 
When you then use the digital out example using the same feed, it successfully calls receive (which calls api/v2/username/feeds/feed_key/data/last to get last value). 

However if you start this example for digitalout on a fresh account (without running the digital input example) then the `digital` feed won't exist (it gets created though), and then later also won't have any data to receive, so the api returns 404. 


Secondly there's a small chance that we have impacted the API when deploying some new functionality which allows accessing a feeds last_value, as a precursor to some Blockly Actions features. Having looked at that section of api code I believe it remains unchanged, but will get confirmation from someone next week. 


Lastly it appears that the guide pages have been rejigged and are missing the dashboard setup instructions, which may have created the expected data (as well as allowing the user to follow the guide and toggle the feed value resulting in the LED change).
I'll pass that along and get the guide fixed up.

The temporary solution is to either try the digital In example first, to create some data, or just send a first datapoint before the while loop, or trap the error on the receive call.

Fixing the digital out example / learn guide it probably makes most sense to just capture the error if no last value, maybe print to serial too.

**Comment by lorennorman** [comment]
The IO team has just updated the error messages for these endpoints. When you request some data from a feed that has none, it will now explain why it returned a 404 instead of giving the generic "not found" error message.

A small improvement, but the Python client can be a bit smarter now that there's more info coming back from the server.
